"use strict";
exports.__esModule = true;
var mobileClass_1 = require("../Fundamentos2/mobileClass");
var mobileLibrary_1 = require("./mobileLibrary");
var myPhone0 = new mobileClass_1.Mobile('Nokia', '3210', 'Nokia', 0.016, 'grey', false, 0, 50);
var myPhone1 = new mobileClass_1.Mobile('iPhone', '3G', 'Apple', 8, 'silver', false, 1, 150);
var myPhone2 = new mobileClass_1.Mobile('Galaxy', '10', 'Samsung', 16, 'black', true, 2, 350);
var myPhone3 = new mobileClass_1.Mobile('Xiaomi', 'Mi 11', 'Xiaomi', 64, 'blue', true, 2, 700);
var mobileArray = [myPhone0, myPhone1, myPhone2, myPhone3];
var myMobileLibrary = new mobileLibrary_1.MobileLibrary("myMobileLibrary", "Palencia", mobileArray);
console.log('\n\n\x1b[35m%s\x1b[0m', '1.Comprobar todos los métodos:\n');
console.log('\x1b[36m%s\x1b[0m', 'a.Métodos get y totalPricesCal:');
console.log('- Nombre:', myMobileLibrary.getName());
console.log('- Listado de móviles', myMobileLibrary.getMobiles().length + ":", myMobileLibrary.getMobiles());
console.log('- Localización:', myMobileLibrary.getLocation());
console.log('- Precio de todos los dispositivos:', myMobileLibrary.getTotalPrice());
console.log('\n\x1b[36m%s\x1b[0m', 'b.Métodos set:');
myMobileLibrary.setName('MyNewMobileLibrary');
myMobileLibrary.setLocation('Lisboa');
var myPhone4 = new mobileClass_1.Mobile('iPhone', '12 Pro', 'Apple', 256, 'purple', true, 4, 1000);
myMobileLibrary.setMobiles(myPhone4);
myMobileLibrary.setTotalPrice(2900);
console.log('- Nombre:', myMobileLibrary.getName());
console.log('- Listado de móviles:', myMobileLibrary.getMobiles().length + ":", myMobileLibrary.getMobiles());
console.log('- Localización:', myMobileLibrary.getLocation());
console.log('- Precio de todos los dispositivos:', myMobileLibrary.getTotalPrice());
